#!/bin/bash

gwarn "Make sure that you booted from the latest Gentoo Minimal CD, otherwise
you may encounter random failures, or trash your data. You have been warned!"

gecho "Setting up networking:"

gecho "Listing network interfaces [ifconfig -a]:"
res=`ifconfig -a` && echo "$res"
r1=`echo "$res" | grep "inet addr" | wc -l`

gecho "Listing kernel routing tables [route]:"
res=`route` && echo "$res"
r2=`echo "$res" | wc -l`

gecho "Testing [ping -c 3 senbonzakura.eu]:"
res=`ping -c 3 senbonzakura.eu` && echo "$res"
r3=`echo "$res" | grep "senbonzakura.eu (77.104.222.122)" | wc -l`
r4=`echo "$res" | grep "0% packet loss" | wc -l`
r5=`echo "$res" | grep "100% packet loss" | wc -l`

fail=0
pass=0
[[ $r1 -lt 2 ]] && fail="$fail+1"
[[ $r2 -lt 4 ]] && fail="$fail+1"
[[ $r3 -lt 4 ]] && fail="$fail+1"
[[ $r5 -eq 1 ]] && pass="$pass+1"
[[ $r5 -eq 1 ]] && fail="$fail+1"
[[ $fail -eq 0 and $pass -eq 0 ]] && gwarn "Networking works but some packages were dropped" && gchat "Do you want to use net-setup (saying no will keep networking as is)? (y/n)" && gread "y" "n"
[[ $fail -gt 0 and $pass -eq 0 ]] && gwarn "Networking failed. Please check if your lan-cable is connected, or set up networking manually." && gchat "Do you want to use net-setup (saying no will keep networking as is)? (y[es]/n[o]/r[etest])" && gread "y" "n" "r"



# No, try gentoo's net-setup utility.
if [ $REPLY -eq "n" ] then
    gchat "Hmm, let's try gentoo's net-setup utility. Choose interface (eth0, eth1, etc.):" && gread
    net-setup $REPLY
    ginfo "Restarting interface" && countdown 3 # same as sleep 3 ale da se prerusit klavesou a neco udelat
    /etc/init.d/net.$REPLY restart
    ginfo "Testing networking with 'ping -c 3 www.gentoo.org && route':"
    ping -c 3 www.gentoo.org && route
    gchat "Did it work? (y/n)" && gread "y" "n"
fi

if [ $REPLY -eq "y" ] then
# Networking for installation is written (/etc/resolv.conf and /etc/init.d/net.eth*). If your networking works now and you'll actually want to use it later on as well, is a good idea to remember the result of 'route' command. This can help you debug networking.
else
# Do nothing (goto menu)
fi;



# List network interfaces. If your network card is detected, there should be
# something besides lo with an "inet addr" entry (i.e. eth0)
ifconfig

# Configure it
#echo tak jak je pozdej v instalaci
/etc/init.d/${livecd_net_interface} restart ;

# Test networking
route
ping -c 3 www.gentoo.org

#Networking for installation is written (/etc/resolv.conf and /etc/init.d/net.eth*). If your networking works now and you'll actually want to use it later on as well, is a good idea to remember the result of 'route' command. This can help you debug networking.



# from here incomplete
pppoe-setup
pppoe-start







# Running '/sbin/ifconfig eth0' should result into something like this:
#
#     eth0      Link encap:Ethernet  HWaddr FE:FD:00:00:00:00
#               BROADCAST NOARP MULTICAST  MTU:1500  Metric:1
#               RX packets:0 errors:0 dropped:0 overruns:0 frame:0
#               TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
#               collisions:0 txqueuelen:0 
#               RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)
#
# meaning that your network card is detected. If you receive
#
#     Code Listing 13: Testing availability of your network card, failed
#
# Then the linux kernel doesn't have a loaded driver to work with your
# network card, so you have to search manually the provided driver modules
# for an  applicable driver:

dmesg | grep eth
dmesg | grep NET
ls /lib/modules/`uname -r`/kernel/drivers/net
#gread livecd_kernel_net_driver "Please type in the module name for your network card from the list above (omit the .ko extension)"
modprobe ${livecd_kernel_net_driver}

# Running 'dmesg' or 'dmesg | grep net' respectively will give you insight
# about what is currently visible to the kernel.
# After you have removed all problems, configure your network again. You
# can't continue far beyond this point without networking enabled.



## !!! nezapomenout nastartovat sshd